"""attempts, their answers, and badges

An attempt is marked against the set version the student was shown; answers
are stored in the item's own option order, never the shuffled one; badges
are unique per student, badge and scope.

Revision ID: 25b36840ba01
Revises: 8d5317d077e4
Create Date: 2026-09-25 02:14:39.917447
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '25b36840ba01'
down_revision: str | None = '8d5317d077e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_attempts_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['learning_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_assignment', 'attempts', ['assignment_id', 'status', 'percent'], unique=False)
    op.create_index('ix_attempts_set_student', 'attempts', ['set_id', 'student_id'], unique=False)
    op.create_index('ix_attempts_student', 'attempts', ['student_id', 'completed_at'], unique=False)
    op.create_table('student_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('badge', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'badge', 'scope', name='uq_student_badges')
    )
    op.create_index('ix_student_badges_student', 'student_badges', ['student_id', 'awarded_at'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=40), nullable=False),
    sa.Column('skill', sa.String(length=64), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'item_id', name='uq_attempt_answers_item')
    )
    op.create_index('ix_attempt_answers_attempt', 'attempt_answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempt_answers_attempt', table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index('ix_student_badges_student', table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index('ix_attempts_student', table_name='attempts')
    op.drop_index('ix_attempts_set_student', table_name='attempts')
    op.drop_index('ix_attempts_assignment', table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
