"""moderation events replace guard events

`guard_events` was never written to. `moderation_events` records every safety
check that acted, with a review status for the admin queue. Any rows the old
table has are carried over as injection findings before it goes.

Revision ID: 5b412374bc49
Revises: b7c4e2a9d130
Create Date: 2026-09-25 03:44:13.457523
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5b412374bc49'
down_revision: str | None = 'b7c4e2a9d130'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('screen', sa.String(length=32), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_moderation_severity'),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'dismissed')", name='ck_moderation_events_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['learning_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_events_created', 'moderation_events', ['created_at'], unique=False)
    op.create_index('ix_moderation_events_queue', 'moderation_events', ['status', 'severity', 'created_at'], unique=False)
    op.create_index('ix_moderation_events_user', 'moderation_events', ['user_id', 'created_at'], unique=False)
    op.execute(
        """
        INSERT INTO moderation_events
            (id, message_id, kind, source, category, severity, rule, screen, findings,
             excerpt, status, note, created_at)
        SELECT id, message_id, 'injection', source, 'none',
               CASE WHEN severity IN ('low', 'medium', 'high') THEN severity ELSE 'low' END,
               guard, guard, findings, '', 'open', '', created_at
        FROM guard_events
        """
    )
    op.drop_index(op.f('ix_guard_events_created'), table_name='guard_events')
    op.drop_table('guard_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('guard', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('guard_events_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('guard_events_pkey'))
    )
    op.create_index(op.f('ix_guard_events_created'), 'guard_events', ['created_at'], unique=False)
    op.drop_index('ix_moderation_events_user', table_name='moderation_events')
    op.drop_index('ix_moderation_events_queue', table_name='moderation_events')
    op.drop_index('ix_moderation_events_created', table_name='moderation_events')
    op.drop_table('moderation_events')
    # ### end Alembic commands ###
