"""learning sets, their versions, and assignments

Quizzes and flashcards as structured items (not HTML), versioned so a shared
version is never edited under a student; and assignments that share a
version with a whole class or some of its groups.

Revision ID: 8d5317d077e4
Revises: 662c4fefe6cd
Create Date: 2026-09-25 01:42:40.618799
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8d5317d077e4'
down_revision: str | None = '662c4fefe6cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('grade_level', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure', sa.Text(), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("purpose IN ('assign', 'practice')", name='ck_learning_sets_purpose'),
    sa.CheckConstraint("status IN ('generating', 'ready', 'failed', 'refused')", name='ck_learning_sets_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_sets_owner', 'learning_sets', ['owner_id', 'archived_at', 'updated_at'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('feedback_mode', sa.String(length=16), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('allow_retakes', sa.Boolean(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('leaderboard_enabled', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("feedback_mode IN ('instant', 'end')", name='ck_assignments_feedback'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['learning_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_class', 'assignments', ['class_id', 'created_at'], unique=False)
    op.create_index('ix_assignments_set', 'assignments', ['set_id'], unique=False)
    op.create_table('learning_set_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('build_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['learning_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'version', name='uq_learning_set_version')
    )
    op.create_table('assignment_groups',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_groups')
    op.drop_table('learning_set_versions')
    op.drop_index('ix_assignments_set', table_name='assignments')
    op.drop_index('ix_assignments_class', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_learning_sets_owner', table_name='learning_sets')
    op.drop_table('learning_sets')
    # ### end Alembic commands ###
