"""podium awarded at

Revision ID: a074e2dcde74
Revises: 25b36840ba01
Create Date: 2026-09-25 02:17:25.366085
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a074e2dcde74'
down_revision: str | None = '25b36840ba01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('ranks_awarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'ranks_awarded_at')
    # ### end Alembic commands ###
