#!/usr/bin/env bash
# Regenerate deploy/nginx/cloudflare-realip.conf from Cloudflare's published
# edge ranges. Cloudflare changes them rarely; re-run this when it announces a
# change, commit the result, and redeploy.
#
#   scripts/cloudflare-realip.sh
set -euo pipefail

out="$(dirname "$0")/../deploy/nginx/cloudflare-realip.conf"
v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"

{
  echo "# Generated by scripts/cloudflare-realip.sh — do not edit by hand."
  echo "#"
  echo "# Every request reaches nginx from a Cloudflare edge address, so without"
  echo "# this \$remote_addr is Cloudflare's and the API's per-IP rate limits would"
  echo "# treat a whole school as one visitor. CF-Connecting-IP carries the real"
  echo "# visitor, and is believed only when the peer is one of these ranges."
  for cidr in $v4 $v6; do
    echo "set_real_ip_from ${cidr};"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$out"

echo "wrote $out"
