/** Suggestions, not a rule — a teacher can type any subject. */
export const SUBJECTS = [
  'Bahasa Melayu',
  'English',
  'Mathematics',
  'Science',
  'Sejarah',
  'Geografi',
  'Pendidikan Islam',
  'Pendidikan Moral',
  'Physics',
  'Chemistry',
  'Biology',
  'Additional Mathematics',
  'Accounting',
  'Economics',
  'Computer Science',
  'Reka Bentuk dan Teknologi',
  'Art',
  'Music',
  'Physical Education',
  'Bahasa Cina',
  'Bahasa Tamil',
] as const
